server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vuedemo
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: vue-demo
mybatis:
  mapper-locations: classpath*:mapper/*.xml